Table Proveedor {
  rut_proveedor nchar(15) [pk]
  nombre_proveedor nchar(50)  [NOT NULL]
  id_comuna tinyint           [NOT NULL]
  direccion  nchar(100)       [NOT NULL]
  web varchar
}

Table Comuna {
  id_comuna tinyint [pk] 
  id_ciudad tinyint     [NOT NULL]
  nombre_comuna varchar [NOT NULL]
}

Table Ciudad {
  id_ciudad tinyint [pk]
  nombre_ciudad nchar(50)
}

Table Cliente {
  rut_cliente nchar(10) [pk]
  nombre_cliente nchar(50) [not null]
  id_comuna tinyint [not null]
  direccion_cliente nchar(100) [not null]
}

Table Telefono {
  numero_telefono nchar(15) [pk]
  rut_cliente nchar(10) [not null]
}




Table Categoria {
  id_categoria varchar [pk] 
  nombre_categoria varchar  [NOT NULL]
}

Table Producto {
  id_producto int [pk]  
  id_categoria tinyint    
  nombre_producto varchar [NOT NULL]
  precio_producto decimal [NOT NULL]
  stock_producto int      [NOT NULL]
}

Table Proveedor_Producto {
  id_producto int       [NOT NULL]
  rut_proveedor varchar [NOT NULL]
  ind_vigente boolean   [NOT NULL]
  fecha_ultima_compra date
}

Table Detalle_boleta {
  correlativo_detalle varchar [pk]  
  id_venta varchar      [NOT NULL]
  precio_venta decimal  
  cantidad_producto int [NOT NULL]
}

Table Boleta {
  id_venta varchar [pk]
  rut_cliente nchar(15)   
  fecha_venta date        [NOT NULL]
  descuento_venta decimal [NOT NULL]
}

Ref: Proveedor_Producto.rut_proveedor > Proveedor.rut_proveedor
Ref: Proveedor_Producto.id_producto > Producto.id_producto
Ref: Producto.id_categoria > Categoria.id_categoria
Ref: Boleta.id_venta < Detalle_boleta.id_venta
Ref: Detalle_boleta.precio_venta > Producto.precio_producto
Ref: Cliente.rut_cliente < Boleta.rut_cliente
Ref: Cliente.id_comuna > Comuna.id_comuna
Ref: Comuna.id_ciudad > Ciudad.id_ciudad
Ref: Telefono.rut_cliente > Cliente.rut_cliente
Ref: Proveedor.id_comuna > Comuna.id_comuna
